=== matusm/Bev.Instruments.Mahr.Millitron/doc/__jsondbmodels/measurementModel_GBC_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MeasurementModel",
  "description": "Relevant data of measurements",
  "type": "object",
  "properties":{
	"softwareID":{
		"description": "",
		"type": "string"
	},
	"clientID":{
		"description": "",
		"type": "string"
	},
	"order":{
		"description": "",
		"type": "object",
		 "properties":{
			"orderID":{
				"description": "",
				"type": "string"
			},
			"description":{
				"description": "",
				"type": "string"
			},
			"t-nr.":{
				"description": "",
				"type": "string"
			},
			"comment":{
				"description": "",
				"type": "string"
			}
		 },
		 "required": [ "orderID", "description", "t-nr.", "comment" ]
	},
	"qm": {
		"description": "",
		"type": "array",
		"items":{
			"type":"string"
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"respPersons":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"personID": {
					"description": "",
					"type": "string"
				},
				"mainSigner": {
					"description": "",
					"type": "boolean"
				}
			},
			"required": [ "personID", "mainSigner" ]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"measurementDevices":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"type": {
					"description": "",
					"type": "string"
				},
				"mdID": {
					"description": "",
					"type": "string"
				}
			},
			"required": [ "type", "mdID" ]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"influenceConditions":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"icID": {
					"description": "",
					"type": "string"
				},
				"label": {
					"description": "",
					"type": "string"
				},
				"abbreviation": {
					"description": "",
					"type": "string"
				},
				"complexReal": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						},
						"deviation": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						}
					},
					"required": [ "unit", "value" ]
				},
				"complexString": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"string": {
									"description": "",
									"type": "string"
								}
							},
							"required": [ "string" ]
						}
					},
					"required": [ "unit", "value" ]
				}
			},
			"allOf": [{ "required": ["icID", "label"] }, { "oneOf": [{ "required": ["complexReal"]}, { "required": ["complexString"]}] }]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"tsID":{
		"description": "",
		"type": "string"
	},
	"tsStart":{
		"description": "",
		"type": "string"
	},
	"tsEnd":{
		"description": "",
		"type": "string"
	},
	"measurementParameters":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"mpID": {
					"description": "",
					"type": "string"
				},
				"label": {
					"description": "",
					"type": "string"
				},
				"abbreviation": {
					"description": "",
					"type": "string"
				},
				"complexReal": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						},
						"deviation": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						}
					},
					"required": [ "unit", "value" ]
				},
				"complexString": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"string": {
									"description": "",
									"type": "string"
								}
							},
							"required": [ "string" ]
						}
					},
					"required": [ "unit", "value" ]
				}
			},
			"allOf": [{ "required": ["mpID", "label"] }, { "oneOf": [{ "required": ["complexReal"]}, { "required": ["complexString"]}] }]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"measurementValues":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"mvID": {
					"description": "",
					"type": "string"
				},
				"label": {
					"description": "",
					"type": "string"
				},
				"rows": {
					"description": "",
					"type": "integer",
					"minimum": 1
				},
				"colums": {
					"description": "",
					"type": "integer",
					"minimum": 1
				},
				"table_labels":{
					"description": "",
					"type": "array",
					"items": {
						"type":"string"
					},
					"minItems": 1
				},
				"table_comments": {
					"description": "",
					"type": "string"
				},
				"values": {
					"description": "",
					"type": "array",
					"items":{
						"description": "",
						"type": "array",
						"items":{
							"description": "",
							"type": "object",
							"properties":{
								"string_value": {
									"description": "",
									"type": "string"
								},
								"value": {
									"description": "",
									"type": "object",
									"properties":{
										"decimalPositions": {
											"description": "",
											"type": "integer",
											"minimum": 0
										},
										"mulitplicator": {
											"description": "",
											"type": "string"
										},
										"float": {
											"description": "",
											"type": "number"
										},
										"sign": {
											"description": "",
											"type": "integer",
											"minimum": -1,
											"maximum": 1
										}
									},
									"required": [ "float", "sign" ]
								}
							},
							"allOf": [{ "required": [ "unit" ] }, { "oneOf": [{ "required": ["value"]}, { "required": ["string_value"]}] }]
						}
					},
					"minItems": 1
				}
			},
			"required": [ "mvID", "label", "rows", "columns", "table_labels", "table_comments", "values" ]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"measurementResults":{
		"description": "",
		"type": "array",
		"items":{
			"type": "object",
			"properties":{
				"mrID": {
					"description": "",
					"type": "string"
				},
				"label": {
					"description": "",
					"type": "string"
				},
				"abbreviation": {
					"description": "",
					"type": "string"
				},
				"complexReal": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						},
						"deviation": {
							"description": "",
							"type": "object",
							"properties":{
								"decimalPositions": {
									"description": "",
									"type": "integer",
									"minimum": 0
								},
								"mulitplicator": {
									"description": "",
									"type": "string"
								},
								"float": {
									"description": "",
									"type": "number"
								},
								"sign": {
									"description": "",
									"type": "integer",
									"minimum": -1,
									"maximum": 1
								}
							},
							"required": [ "float", "sign" ]
						}
					},
					"required": [ "unit", "value" ]
				},
				"complexString": {
					"description": "",
					"type": "object",
					"properties":{
						"unit": {
							"description": "",
							"type": "string"
						},
						"value": {
							"description": "",
							"type": "object",
							"properties":{
								"string": {
									"description": "",
									"type": "string"
								}
							},
							"required": [ "string" ]
						}
					},
					"required": [ "unit", "value" ]
				}
			},
			"allOf": [{ "required": ["mrID", "label"] }, { "oneOf": [{ "required": ["complexReal"]}, { "required": ["complexString"]}] }]
		},
		"minItems": 1,
		"uniqueItems": true
	},
	"error":{
		"description": "",
		"type": "array",
		"items":{
			"type":"string"
		},
		"minItems": 0,
		"uniqueItems": true
	}	
  },
  "required": [ "softwareID", "clientID", "order", "qm", "respPersons", "measurementDevices", "influenceConditions", "tsID", "tsStart", "tsEnd", "measurementParameters", "measurementValues", "measurementResults", "error" ]
}

=== matusm/Bev.Instruments.Mahr.Millitron/doc/__jsondbmodels/measurementModel_GBC_20230906-0519_OntologyMapping.json
{
	"softwareID": "BE230SM0001R0002",
	"clientID": "W003-E2-M-N58",
	"order": {
		"orderID": "XXX",
		"description": "Messung für ersten Programm-Test",
		"t-nr.": "keine (Hoheit)",
		"comment": "keine Endmaß-Bewegung, Antastung immer am gleichen Punkt"
	},
	"qm": [
		"A_011203"
	],
	"respPersons": [
		{
			"personID": "matus",
			"mainSigner": true
		},
		{
			"personID": "premper",
			"mainSigner": false
		}
	],
	"measurementDevices": [
		{
			"type": "examinee",
			"mdID": "MD000001"
		},
		{
			"type": "normal",
			"mdID": "MD000001"
		},
		{
			"type": "environment",
			"mdID": "MD000002"
		}
	],
	"influenceConditions": [
		{
			"icID": "IC000001",
			"label": "air_temperature_laboratory",
			"complexReal": {
				"unit": "_degreecelsius",
				"value": {
					"decimalPositions": 2,
					"float": 19.87,
					"sign": 1
				},
				"deviation": {
					"decimalPositions": 2,
					"float": 0.07,
					"sign": 0
				}
			}
		},
		{
			"icID": "IC000002",
			"label": "temperature_drift",
			"complexReal": {
				"unit": "_degreecelsius",
				"value": {
					"decimalPositions": 2,
					"float": 0.12,
					"sign": -1
				}
			}
		},
		{
			"icID": "IC000003",
			"label": "air_humidity_laboratory",
			"complexReal": {
				"unit": "_percentage",
				"value": {
					"decimalPositions": 0,
					"float": 43,
					"sign": 1
				},
				"deviation": {
					"decimalPositions": 0,
					"float": 0.0,
					"sign": 0
				}
			}
		}
	],
	"tsID": "TS000001",
	"tsStart": "1701162396",
	"tsEnd": "1701164396",
	"measurementParameters": [
		{
			"mpID": "MP000001",
			"label": "nominal_length",
			"complexReal": {
				"unit": "_milli_meter",
				"value": {
					"decimalPositions": 0,
					"float": 80.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000002",
			"label": "deviation_normal",
			"complexReal": {
				"unit": "_micro_meter",
				"value": {
					"decimalPositions": 3,
					"float": 0.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000003",
			"label": "flattening_correction",
			"complexReal": {
				"unit": "_micro_meter",
				"value": {
					"decimalPositions": 3,
					"float": 0.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000004",
			"label": "material_examinee",
			"complexString": {
				"unit": "_none",
				"value": {
					"string": "ceramics_psz"
				}
			}
		},
		{
			"mpID": "MP000005",
			"label": "material_normal",
			"complexString": {
				"unit": "_none",
				"value": {
					"string": "ceramics_psz"
				}
			}
		},
		{
			"mpID": "MP000006",
			"label": "temperature_examinee",
			"complexReal": {
				"unit": "_degreecelsius",
				"value": {
					"decimalPositions": 3,
					"float": 19.902,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000007",
			"label": "temperature_normal",
			"complexReal": {
				"unit": "_degreecelsius",
				"value": {
					"decimalPositions": 3,
					"float": 19.902,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000008",
			"label": "alpha_examinee",
			"complexReal": {
				"unit": "_partspermillion_kelvin_tothe{1}",
				"value": {
					"decimalPositions": 1,
					"float": 9.3,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000009",
			"label": "alpha_normal",
			"complexReal": {
				"unit": "_partspermillion_kelvin_tothe{1}",
				"value": {
					"decimalPositions": 1,
					"float": 9.3,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000A",
			"label": "temperature_correction",
			"complexReal": {
				"unit": "_micro_meter",
				"value": {
					"decimalPositions": 3,
					"float": 0.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000B",
			"label": "measurement_cycles_center_dimension",
			"complexReal": {
				"unit": "_none",
				"value": {
					"decimalPositions": 0,
					"float": 5.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000C",
			"label": "measurement_cycles_deviation_margin",
			"complexReal": {
				"unit": "_none",
				"value": {
					"decimalPositions": 0,
					"float": 3.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000D",
			"label": "measurement_cycle_timeout",
			"complexReal": {
				"unit": "_second",
				"value": {
					"decimalPositions": 0,
					"float": 8.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000E",
			"label": "button_stroke_time",
			"complexReal": {
				"unit": "_second",
				"value": {
					"decimalPositions": 0,
					"float": 1.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP00000F",
			"label": "threshold_center_dimension",
			"complexReal": {
				"unit": "_nano_meter",
				"value": {
					"decimalPositions": 0,
					"float": 21.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000010",
			"label": "threshold_deviation_margin",
			"complexReal": {
				"unit": "_nano_meter",
				"value": {
					"decimalPositions": 0,
					"float": 21.0,
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000011",
			"label": "correction_factor_button_a",
			"complexReal": {
				"unit": "_none",
				"value": {
					"decimalPositions": 4,
					"float": 0.9998,
					"mulitplicator": "_ten_tothe{1}",
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000012",
			"label": "correction_factor_button_b",
			"complexReal": {
				"unit": "_none",
				"value": {
					"decimalPositions": 4,
					"float": 1.0,
					"mulitplicator": "_ten_tothe{1}",
					"sign": 1
				}
			}
		},
		{
			"mpID": "MP000013",
			"label": "measurement_value_integration_time",
			"complexReal": {
				"unit": "_second",
				"value": {
					"decimalPositions": 4,
					"float": 0.1024,
					"sign": 1
				}
			}
		}
	],
	"measurementValues": [
		{
			"mvID": "MV000001",
			"label": "measurement_values_center_dimension",
			"rows": 5,
			"columns": 6,
			"table_labels": [
				"N",
				"P",
				"P",
				"N",
				"Drift",
				"P-N"
			],
			"table_comments": "",
			"values": [
				[
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 57.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 55.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 56.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 55.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 0.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 1.0,
							"sign": -1
						}
					}
				],
				[
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 57.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 56.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 56.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 55.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 0.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 1.0,
							"sign": -1
						}
					}
				]
			]
		},
		{
			"mvID": "MV000002",
			"label": "measurement_values_center_dimension_evaluation",
			"rows": 1,
			"columns": 3,
			"table_labels": [
				"Mittel(P-N)",
				"Sigma",
				"Span/Range"
			],
			"table_comments": "",
			"values": [
				[
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 1,
							"float": 1.3,
							"sign": -1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 1,
							"float": 1.9,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 1,
							"float": 4.5,
							"sign": 1
						}
					}
				]
			]
		},
		{
			"mvID": "MV000003",
			"label": "five_point_measurement",
			"rows": 7,
			"columns": 4,
			"table_labels": [
				"Reference",
				"Reference Length",
				"Sigma",
				"Span/Range"
			],
			"table_comments": "1 Wiederholmessung",
			"values": [
				[
					{
						"unit": "_none",
						"string_value": "A-M"
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 1.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 2.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 3.0,
							"sign": 1
						}
					}
				],
				[
					{
						"unit": "_none",
						"string_value": "B-M"
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 0.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 1.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 2.0,
							"sign": 1
						}
					}
				],
				[
					{
						"unit": "_none",
						"string_value": "B-M"
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 0.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 1.0,
							"sign": 1
						}
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 2.0,
							"sign": 1
						}
					}
				],
				[
					{
						"unit": "_none",
						"string_value": "f_o"
					},
					{
						"unit": "_nano_meter",
						"value": {
							"decimalPositions": 0,
							"float": 4.0,
